---
info:
  title: BoardgameTracker
  version: 0.1
  description: API for tracking game results
servers: ''
components:
  schemas:
    Match:
      type: object
      properties:
        date:
          description: When the match was played
          type: datetime
        turns:
          description: Number of turns in the match
          type: integer
    Player:
      type: object
      properties:
        name:
          description: Name of the player
          type: string
    Game:
      type: object
      properties:
        name:
          description: Name of the game
          type: string
    Map:
      type: object
      properties:
        name:
          description: Name of the map
          type: string
    Ruleset:
      type: object
      properties:
        name:
          description: Name of the ruleset
          type: string
    Team:
      type: object
      properties:
        name:
          description: Name of the team
          type: string

  parameters:
    date:
      description: date of the match
      name: date
      schema:
        type: datetime
    turns:
      description: turns of the match
      name: turns
      schema:
        type: integer
    game_name:
      description: Name of the existing game
      in: path
      name: game
      required: true
      schema:
        type: string
    map_id:
      description: Id of the existing map
      in: path
      name: map_
      required: true
      schema:
        type: integer
    map_name:
      description: Name of the existing map
      in: path
      name: map_
      required: true
      schema:
        type: string
    ruleset_id:
      description: Id of the existing ruleset
      in: path
      name: ruleset
      required: true
      schema:
        type: integer
    ruleset_name:
      description: Name of the existing ruleset
      in: path
      name: ruleset
      required: true
      schema:
        type: string
    team_name:
      description: Name of the existing team
      in: path
      name: team
      required: true
      schema:
        type: string