---
info:
  title: BoardgameTracker
  version: 0.1
  description: API for tracking game results
servers: ''
components:
  schemas:
    Match:
      type: object
      properties:
        date:
          description: When the match was played
          type: datetime
        turns:
          description: Number of turns in the match
          type: integer
        game_id:
          description: Game's id
          type: integer
        map_id:
          description: Map's id
          type: integer
        ruleset_id:
          description: Ruleset's id
          type: integer
    Player:
      type: object
      properties:
        name:
          description: Name of the player
          type: string
    Game:
      type: object
      properties:
        name:
          description: Name of the game
          type: string
    Map:
      type: object
      properties:
        name:
          description: Name of the map
          type: string
    Ruleset:
      type: object
      properties:
        name:
          description: Name of the ruleset
          type: string
    Team:
      type: object
      properties:
        name:
          description: Name of the team
          type: string
    PlayerResult:
      type: object
      properties:
        points:
          description: Player's points
          type: number
        player_id:
          description: ID of player
          type: integer
        match_id:
          in: path
          description: ID of match
          type: integer
        team_id:
          description: ID of team
          type: integer
    TeamResult:
      properties:
        points:
          description: Team's points
          type: number
        order:
          description: Finishing order of the team
          type: integer
        match_id:
          in: path
          description: ID of match
          type: integer
        team_id:
          description: ID of team
          type: integer

  parameters:
    match_id:
      description: Match id
      in: path
      name: match
      required: true
      schema:
        type: integer
    date:
      description: date of the match
      name: date
      schema:
        type: datetime
    turns:
      description: turns of the match
      name: turns
      schema:
        type: integer
    game_name:
      description: Name of the existing game
      in: path
      name: game
      required: true
      schema:
        type: string
    map_id:
      description: Id of the existing map
      in: path
      name: map_
      required: true
      schema:
        type: integer
    map_name:
      description: Name of the existing map
      in: path
      name: map_
      required: true
      schema:
        type: string
    ruleset_id:
      description: Id of the existing ruleset
      in: path
      name: ruleset
      required: true
      schema:
        type: integer
    ruleset_name:
      description: Name of the existing ruleset
      in: path
      name: ruleset
      required: true
      schema:
        type: string
    team_name:
      description: Name of the existing team
      in: path
      name: team
      required: true
      schema:
        type: string
    player_name:
      description: Name of an existing player
      in: path
      name: player
      required: true
      schema:
        type: string
    player_result_id:
      description: Row of player results
      in: path
      name: player_result
      required: true
      schema:
        type: integer
    team_result_id:
      description: Row of team results
      in: path
      name: team_result
      required: true
      schema:
        type: integer