---
info:
  title: BoardgameTracker
  version: 0.1
  description: API for tracking game results
servers: ''
components:
  schemas:
    Match:
      type: object
      properties:
        date:
          description: When the match was played
          type: datetime
        turns:
          description: Number of turns in the match
          type: integer

  parameters:
    date:
      description: date of the match
      name: date
      schema:
        type: datetime
    turns:
      description: turns of the match
      name: turns
      schema:
        type: integer
